# Generated by Django 2.2.5 on 2019-09-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plot', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ForeignKey(on_delete='CASCADE', related_name='casted_on', to='movies.Actor')),
            ],
        ),
    ]
