# Generated by Django 2.2.5 on 2019-09-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190910_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_img',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
